[FIX] Bump supported python versions
Python 2.7 is no longer officially supported and it was removed from
setup-python. https://github.com/actions/setup-python/issues/672.

Python 3.5 and 3.6 aren't really used neither, and CI is currently failing due
to:

```
Version 3.5 was not found in the local cache
Error: The version '3.5' with architecture 'x64' was not found for Ubuntu 22.04.
```

In any case, packages up to marabunta<=0.10.6 have been published and do support
these deprecated python versions.