Disable interactive mode when stdout is not a tty
As mentioned in #5, if stdout is not a tty, we got the following error:

termios.error: (25, 'Inappropriate ioctl for device')

The correction is to degrade to a non-interactive mode when we don't
have a tty, which is detected with 'sys.stdout.isatty()' as proposed by
@lepistone.